<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.example.bamoe.poc</groupId>
  <artifactId>customer-rule-poc</artifactId>
  <version>1.0.0-SNAPSHOT</version>

  <properties>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

    <!-- Versions -->
    <version.org.springframework.boot>4.0.7</version.org.springframework.boot>
    <version.bamoe>9.5.0-ibm-0005</version.bamoe>
    <version.bamoe.plugins>9.5.0-ibm-0005</version.bamoe.plugins>

  </properties>

  <dependencyManagement>
    <dependencies>
       <!--
         The BAMOE Spring Boot BOM manages all Spring Boot-specific dependencies required to create
         Business Services — including Apache KIE, Drools, jBPM, Kogito, and BAMOE extensions
       -->
      <dependency>
        <groupId>com.ibm.bamoe</groupId>
        <artifactId>bamoe-spring-boot-bom</artifactId>
        <version>${version.bamoe}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <!-- BAMOE ILMT -->
    <!-- Uncomment for non-containerized deployments only -->
    <!--
    <dependency>
      <groupId>com.ibm.bamoe</groupId>
      <artifactId>bamoe-ilmt-compliance-spring-boot-dmoe</artifactId>
    </dependency>
    -->

    <!-- Kogito Core -->
    <dependency>
      <groupId>org.jbpm</groupId>
      <artifactId>jbpm-with-drools-spring-boot-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>kogito-rest-workitem</artifactId>
    </dependency>
    <!-- Spring Boot -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
      <optional>true</optional>
    </dependency>

    <!-- Testing -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>

    <!-- Kogito Testing -->
    <dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>kogito-scenario-simulation</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <finalName>${project.artifactId}</finalName>
    <plugins>
      <plugin>
        <groupId>org.kie.kogito</groupId>
        <artifactId>kogito-maven-plugin</artifactId>
        <version>${version.bamoe.plugins}</version>
        <executions>
          <execution>
            <goals>
              <goal>generateModel</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <version>${version.org.springframework.boot}</version>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
