apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-rule-poc
  labels:
    app.kubernetes.io/part-of: bamoe-customer-rule-poc
data:
  SPRING_PROFILES_ACTIVE: "ocp"
  JAVA_TOOL_OPTIONS: >-
    -XX:MaxRAMPercentage=70.0
    -XX:InitialRAMPercentage=25.0
    -Djava.io.tmpdir=/tmp
  MANAGEMENT_SERVER_PORT: "8081"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_GROUP_LIVENESS_INCLUDE: "livenessState"
  MANAGEMENT_ENDPOINT_HEALTH_GROUP_READINESS_INCLUDE: "readinessState"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
  SERVER_SHUTDOWN: "graceful"
  SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE: "30s"
  BAMOE_CORS_ALLOWED_ORIGIN_PATTERNS: "https://bamoe-management-console.apps.itz-ygi22x.infra01-lb.wdc07.techzone.ibm.com"
