apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bamoe-runtime

resources:
  - ../../base
  - ../../route
  - mock-alias.yaml

patches:
  - path: license.yaml

images:
  - name: customer-rule-poc
    newName: ghcr.io/jihunkeom/customer-rule-poc
    newTag: DO_NOT_APPLY_SET_IMMUTABLE_REF