apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-rule-poc
spec:
  template:
    metadata:
      annotations:
        productName: "IBM Process Automation Manager Open Edition"
        productID: "72984f114b54496a8a44be139154a988"
        productVersion: "9.5.0"
        productMetric: "VIRTUAL_PROCESSOR_CORE"
        includeSWCUpload: "true"
