apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: customer-rule-poc
  labels:
    app.kubernetes.io/part-of: bamoe-customer-rule-poc
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: customer-rule-mock
  labels:
    app.kubernetes.io/part-of: bamoe-customer-rule-poc
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: customer-rule-poc
  labels:
    app.kubernetes.io/part-of: bamoe-customer-rule-poc
spec:
  runPolicy: Serial
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: customer-rule-poc:latest
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: customer-rule-mock
  labels:
    app.kubernetes.io/part-of: bamoe-customer-rule-poc
spec:
  runPolicy: Serial
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: mock-server/Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: customer-rule-mock:latest
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
