apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-deployer
  labels:
    app.kubernetes.io/part-of: bamoe-customer-rule-poc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-deployer
  labels:
    app.kubernetes.io/part-of: bamoe-customer-rule-poc
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames:
      - customer-rule-poc
      - customer-rule-mock
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-deployer
  labels:
    app.kubernetes.io/part-of: bamoe-customer-rule-poc
subjects:
  - kind: ServiceAccount
    name: github-actions-deployer
    namespace: bamoe-poc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-actions-deployer
